### Call to upper case
POST http://localhost:7071/api/upper HTTP/1.1

poland

### Call to remote

POST https://camel-20180503110100788.azurewebsites.net/api/upper HTTP/1.1

England

### Split message and send to Kafka
POST http://localhost:7071/api/messageSplitter HTTP/1.1
Content-Type: application/json
Accept-Encoding: UTF-8
Split-Pattern: $.codes[*]
Destination: http://localhost:7071/api/queueOnKafka
Destination-Method: POST

{
    "codes": ["FOO", "BAR", "BEER", "WINE"]
}


### Filter message



### Split message to Upper Case
POST http://localhost:7071/api/messageSplitter HTTP/1.1
Content-Type: application/json
Accept-Encoding: UTF-8
Split-Pattern: $.codes[*]
Destination: http://localhost:7071/api/upper
Destination-Method: POST

{
    "codes": ["abc", "xyz", "aqowibnvf", "tbsaidbuasi"]
}