### HTTP Calls for Testing

### Variables
@local = http://localhost:7071
@remote = https://camel-20180503110100788.azurewebsites.net
@url = http://localhost:7071

### Call to upper case
POST {{url}}/api/upper HTTP/1.1

netherlands

### Split message and send to Kafka
POST {{url}}/api/messageSplitter HTTP/1.1
Content-Type: application/json
Accept-Encoding: UTF-8
Split-Pattern: $.codes[*]
Destination: {{url}}/api/queueOnKafka
Destination-Method: POST

{
    "codes": ["NETHERLANDS", "AMSTERDAM", "UTRECHT", "AMHEIN"]
}

### Split message to Upper Case
POST {{url}}/api/messageSplitter HTTP/1.1
Content-Type: application/json
Accept-Encoding: UTF-8
Split-Pattern: $.codes[*]
Destination: {{url}}/api/upper
Destination-Method: POST

{
    "codes": ["abc", "xyz", "aqowibnvf", "tbsaidbuasi"]
}
